-- EcoBite MVP — esquema Postgres / Supabase
-- Basado en docs/proyecto_ecobite/assets/modelo_datos.jpg
-- Columnas extra de la semana 2: activo, zona, distancia_km, tipo_envase.
-- transporte_sin_emision y estado_simulado ya estaban en el diagrama;
-- acá quedan restringidos a los valores de negocio.
--
-- Volver a ejecutar este archivo borra las tablas y los datos.
-- Después hay que correr 002_seed.sql.

BEGIN;

DROP TABLE IF EXISTS metricas_impacto CASCADE;
DROP TABLE IF EXISTS detalle_pedidos CASCADE;
DROP TABLE IF EXISTS pedidos CASCADE;
DROP TABLE IF EXISTS platillos CASCADE;
DROP TABLE IF EXISTS restaurantes CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TYPE IF EXISTS rol_usuario CASCADE;

CREATE TYPE rol_usuario AS ENUM ('cliente', 'dueno', 'admin');

CREATE TABLE usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    rol rol_usuario NOT NULL,
    fecha_registro TIMESTAMPTZ NOT NULL
);

CREATE TABLE restaurantes (
    id_restaurante INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario_owner INTEGER NOT NULL UNIQUE REFERENCES usuarios (id_usuario),
    nombre VARCHAR(120) NOT NULL,
    direccion TEXT NOT NULL,
    envase_biodegradable BOOLEAN NOT NULL,
    indicador_eco VARCHAR(50) NOT NULL,
    activo BOOLEAN NOT NULL
);

CREATE TABLE platillos (
    id_platillo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_restaurante INTEGER NOT NULL REFERENCES restaurantes (id_restaurante),
    nombre VARCHAR(100) NOT NULL,
    precio DECIMAL(10, 2) NOT NULL CHECK (precio >= 0),
    co2_ahorrado_unit DECIMAL(8, 2) NOT NULL CHECK (co2_ahorrado_unit >= 0),
    disponible BOOLEAN NOT NULL
);

CREATE TABLE pedidos (
    id_pedido INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario_cliente INTEGER NOT NULL REFERENCES usuarios (id_usuario),
    id_restaurante INTEGER NOT NULL REFERENCES restaurantes (id_restaurante),
    fecha_pedido TIMESTAMPTZ NOT NULL,
    estado_simulado VARCHAR(30) NOT NULL CHECK (
        estado_simulado IN ('pending', 'completed', 'cancelled')
    ),
    transporte_sin_emision VARCHAR(50) NOT NULL CHECK (
        transporte_sin_emision IN ('bike', 'ev')
    ),
    total DECIMAL(10, 2) NOT NULL CHECK (total >= 0),
    co2_total_ahorrado DECIMAL(8, 2) NOT NULL CHECK (co2_total_ahorrado >= 0),
    zona VARCHAR(50) NOT NULL,
    distancia_km DECIMAL(8, 2) NOT NULL CHECK (distancia_km > 0),
    CONSTRAINT pedidos_co2_kpi_chk CHECK (
        (
            estado_simulado <> 'completed'
            AND co2_total_ahorrado = 0
        )
        OR (
            estado_simulado = 'completed'
            AND transporte_sin_emision = 'bike'
            AND co2_total_ahorrado = round(distancia_km * 0.17::numeric, 2)
        )
        OR (
            estado_simulado = 'completed'
            AND transporte_sin_emision = 'ev'
        )
    )
);

CREATE TABLE detalle_pedidos (
    id_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INTEGER NOT NULL REFERENCES pedidos (id_pedido),
    id_platillo INTEGER NOT NULL REFERENCES platillos (id_platillo),
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    precio_unitario DECIMAL(10, 2) NOT NULL CHECK (precio_unitario >= 0),
    co2_subtotal DECIMAL(8, 2) NOT NULL CHECK (co2_subtotal >= 0),
    tipo_envase VARCHAR(20) NOT NULL CHECK (
        tipo_envase IN ('biodegradable', 'plastico')
    )
);

CREATE TABLE metricas_impacto (
    id_metrica INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INTEGER NOT NULL UNIQUE REFERENCES pedidos (id_pedido),
    id_usuario INTEGER NOT NULL REFERENCES usuarios (id_usuario),
    co2_evitado_kg DECIMAL(8, 2) NOT NULL CHECK (co2_evitado_kg >= 0),
    fecha_calculo TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_platillos_restaurante ON platillos (id_restaurante);
CREATE INDEX idx_pedidos_usuario ON pedidos (id_usuario_cliente);
CREATE INDEX idx_pedidos_restaurante ON pedidos (id_restaurante);
CREATE INDEX idx_detalle_pedido ON detalle_pedidos (id_pedido);
CREATE INDEX idx_detalle_platillo ON detalle_pedidos (id_platillo);
CREATE INDEX idx_metricas_usuario ON metricas_impacto (id_usuario);

-- Sin políticas, anon y authenticated no leen filas (incluido password_hash).
-- La conexión de Prisma usa el usuario de la base y no pasa por estas políticas.
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE restaurantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE platillos ENABLE ROW LEVEL SECURITY;
ALTER TABLE pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE detalle_pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE metricas_impacto ENABLE ROW LEVEL SECURITY;

COMMENT ON COLUMN platillos.co2_ahorrado_unit IS
    'Dato de catálogo del diagrama. No alimenta el KPI de CO2 de la semana 2.';
COMMENT ON COLUMN detalle_pedidos.co2_subtotal IS
    'co2_ahorrado_unit * cantidad. No alimenta el KPI de CO2 de la semana 2.';
COMMENT ON COLUMN pedidos.co2_total_ahorrado IS
    'KPI: distancia_km * 0.17 si estado_simulado = completed y transporte_sin_emision = bike; si no, 0.';
COMMENT ON COLUMN pedidos.distancia_km IS
    'Promedio fijo de la zona, en km. No hay GPS en el MVP.';

COMMIT;
